# Generated by Django 5.0.1 on 2024-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.BigIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('ccode', models.BigIntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('updateaccess', models.BooleanField()),
                ('deleteaccess', models.BooleanField()),
                ('createaccess', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccode', models.BigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ccode', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('pstatus', models.CharField(max_length=255)),
                ('startline', models.DateField()),
                ('deadline', models.DateField()),
                ('profit', models.BigIntegerField()),
                ('description', models.TextField()),
                ('tasks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('empid', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
